var svg = d3.select("#legend-4")
    .append("svg")
    .attr("viewBox", [0, 0, 900, 30]);

    svg.append("circle").attr("cx",5).attr("cy",5).attr("r", 5).style("fill", "#ca0020")
    svg.append("circle").attr("cx",100).attr("cy",5).attr("r", 5).style("fill", "#ff6880")
    svg.append("circle").attr("cx",240).attr("cy",5).attr("r", 5).style("fill", "#9765ad")
    svg.append("circle").attr("cx",325).attr("cy",5).attr("r", 5).style("fill", "#58befa")
    svg.append("circle").attr("cx",470).attr("cy",5).attr("r", 5).style("fill", "#0571b0")
    svg.append("circle").attr("cx",560).attr("cy",5).attr("r", 5).style("fill", "#757C80")
    svg.append("circle").attr("cx",660).attr("cy",5).attr("r", 5).style("fill", "#fff").style("stroke", "#757C80").style("stroke-width", 0.5)
    svg.append("text").attr("x", 15).attr("y", 5).text("Republican").style("font-size", "12px").attr("alignment-baseline","middle")
    svg.append("text").attr("x", 110).attr("y", 5).text("Bipartisan - mostly R").style("font-size", "12px").attr("alignment-baseline","middle")
    svg.append("text").attr("x", 250).attr("y", 5).text("Bipartisan").style("font-size", "12px").attr("alignment-baseline","middle")
    svg.append("text").attr("x", 335).attr("y", 5).text("Bipartisan - mostly D").style("font-size", "12px").attr("alignment-baseline","middle")
    svg.append("text").attr("x", 480).attr("y", 5).text("Democrat").style("font-size", "12px").attr("alignment-baseline","middle")
    svg.append("text").attr("x", 570).attr("y", 5).text("Independent").style("font-size", "12px").attr("alignment-baseline","middle")
    svg.append("text").attr("x", 670).attr("y", 5).text("Unspecified").style("font-size", "12px").attr("alignment-baseline","middle")
    svg.append("text").attr("x", 2).attr("y", 30).text("Total Donations given in thousands of $").style("font-size", "12px")